import { Router } from "express";
import { authRoutes } from "../modules/auth/auth.routes";
import { societiesRoutes } from "../modules/societies/societies.routes";
import { residentsRoutes } from "../modules/residents/residents.routes";
import { unitsRoutes } from "../modules/units/units.routes";
import { servicesRoutes } from "../modules/services/services.routes";
import { workersRoutes } from "../modules/workers/workers.routes";
import { bookingsRoutes } from "../modules/bookings/bookings.routes";
import { notificationsRoutes } from "../modules/notifications/notifications.routes";
import { grievancesRoutes, adminGrievancesRoutes } from "../modules/grievances/grievances.routes";
import { visitorsRoutes, gateRoutes, adminVisitorsRoutes } from "../modules/visitors/visitors.routes";
import { paymentsWebhookRoutes, paymentsRoutes, adminPaymentsRoutes } from "../modules/payments/payments.routes";
import { analyticsRoutes } from "../modules/analytics/analytics.routes";
import { eventsRoutes, adminEventsRoutes } from "../modules/events/events.routes";
import { announcementsRoutes, adminAnnouncementsRoutes } from "../modules/announcements/announcements.routes";
import { documentsRoutes, adminDocumentsRoutes } from "../modules/documents/documents.routes";
import { forumRoutes, adminForumRoutes } from "../modules/forum/forum.routes";
import { emergencyRoutes, adminEmergencyRoutes } from "../modules/emergency/emergency.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRoutes);
apiRouter.use("/society", societiesRoutes);
apiRouter.use("/admin/residents", residentsRoutes);
apiRouter.use("/admin/units", unitsRoutes);
apiRouter.use("/services", servicesRoutes);
apiRouter.use("/admin/workers", workersRoutes);
apiRouter.use("/bookings", bookingsRoutes);
apiRouter.use("/notifications", notificationsRoutes);
apiRouter.use("/grievances", grievancesRoutes);
apiRouter.use("/admin/grievances", adminGrievancesRoutes);
apiRouter.use("/visitors", visitorsRoutes);
apiRouter.use("/gate", gateRoutes);
apiRouter.use("/admin/visitors", adminVisitorsRoutes);
// Webhook router mounted before the authenticated one at the same prefix — see payments.routes.ts.
apiRouter.use("/payments", paymentsWebhookRoutes);
apiRouter.use("/payments", paymentsRoutes);
apiRouter.use("/admin/payments", adminPaymentsRoutes);
apiRouter.use("/admin/analytics", analyticsRoutes);
apiRouter.use("/events", eventsRoutes);
apiRouter.use("/admin/events", adminEventsRoutes);
apiRouter.use("/announcements", announcementsRoutes);
apiRouter.use("/admin/announcements", adminAnnouncementsRoutes);
apiRouter.use("/documents", documentsRoutes);
apiRouter.use("/admin/documents", adminDocumentsRoutes);
apiRouter.use("/forum", forumRoutes);
apiRouter.use("/admin/forum", adminForumRoutes);
apiRouter.use("/emergency", emergencyRoutes);
apiRouter.use("/admin/emergency", adminEmergencyRoutes);
